### ISSUE TITLE
Switching to Monaco Editor broke the app

### ISSUE THREAD

**Issue by EFXAlexLong** [chinchang/web-maker#402]
## Meta info

- Is this a bug or suggestion?: Bug
- Version (click on help icon in footer): 4.0.1
- Context - Web app, Chrome extension or both?: Web app

I was working on a new project in Files Mode, when I decided to try enabling Monaco on a whim. It borked everything, maybe except the editor area. Monaco works, but the current file's tab doesn't appear, and no UI element save for file names in the sidebar are interactive. I cannot open settings to revert back to Codemirror after refreshing the app. I notice in the browser Dev Tools console that there's a message "ReferenceError: monaco is not defined". I've tried this in is Mozilla Firefox, and have not tried replicating this using the Chrome extension.

**Comment by chinchang** [comment]
Looking into this.

**Comment by EFXAlexLong** [comment]
Thanks! BTW, is there another way to restore the default settings without having access to the settings screen (and not wiping out any projects)?

**Comment by chinchang** [comment]
I just pushed version 4.0.2 which comes with setting override ability through query parameters.
Open the web app like so: `https://webmaker.app/app/?settings=isMonacoEditorOn:false`
This will stop monaco from being used. Once the web app opens, go to settings, disabled monaco from there.

Let me know if any issue.

**Comment by EFXAlexLong** [comment]
It's looks like Monaco is disabled, however the UI is still broken, and so I cannot get to Settings. No editor loads when reloading the app using that URL, actually.

I do think I resolved the need to revert back to CodeMirror. I opened Firefox's Developer Tools > Storage > Local Storage > webmaker.app. I found the "isMonacoEditorOn" key and changed the value to false. Reloaded the app after, and viola! I assume that this is not necessarily recommended, but I figured it wouldn't hurt to modify since editing any project wasn't possible otherwise.

**Comment by chinchang** [comment]
Great. Glad it fixed for you. I'll fix the root issue and update here too.
